apiVersion: 1
datasources:
  - name: ClickHouse
    uid: clickhouse-crypto
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      server: clickhouse
      port: 8123
      username: default
      defaultDatabase: binance
      protocol: http
    isDefault: true
